version: '3.8'
services:
  holamundo:
    build:
      context: ./holamundo-micro
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: holamundo_container

  holaspider:
    build:
      context: ./spider-micro
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    container_name: holaspider_container

  horamicro:
    build:
      context: ./hora-micro
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    container_name: horamicro_container
  
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    container_name: product_service_container

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    container_name: email_service_container
