version: '3.8'
services:
  holamundo:
    build:
      context: ./holamundo-micro
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: holamundo_container

  holaspider:
    build:
      context: ./spider-micro
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    container_name: holaspider_container

  horamicro:
    build:
      context: ./hora-micro
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    container_name: horamicro_container