name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build holamundo-micro
      run: |
        cd holamundo-micro
        mvn clean package
        ls -al target

    - name: Build hora-micro
      run: |
        cd hora-micro
        mvn clean package
        ls -al target

    - name: Build spider-micro
      run: |
        cd spider-micro
        mvn clean package
        ls -al target

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push holamundo-micro to DockerHub
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/holamundo-micro:latest -f holamundo-micro/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/holamundo-micro:latest

    - name: Build and push hora-micro to DockerHub
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hora-micro:latest -f hora-micro/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hora-micro:latest

    - name: Build and push spider-micro to DockerHub
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spider-micro:latest -f spider-micro/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/spider-micro:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Tag and push holamundo-micro to ECR
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/holamundo-micro:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/holamundo-micro:latest
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/holamundo-micro:latest

    - name: Tag and push hora-micro to ECR
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/hora-micro:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/hora-micro:latest
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/hora-micro:latest

    - name: Tag and push spider-micro to ECR
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/spider-micro:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/spider-micro:latest
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/spider-micro:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_KEY }}
        script: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
          docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/holamundo-micro:latest
          docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/hora-micro:latest
          docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/spider-micro:latest
          docker-compose -f docker-compose.yml up -d --remove-orphans
